apiVersion: v1
kind: Service
metadata:
  name: account-service
spec:
  selector:
    app: account-service
    tier: backend
  ports:
  - protocol: TCP
    port: 8080
    targetPort: http

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: account-service
spec:
  selector:
    matchLabels:
      app: account-service
      tier: backend
      track: stable
  replicas: 1
  template:
    metadata:
      labels:
        app: account-service
        tier: backend
        track: stable
    spec:
      containers:
      - name: account
        image: demo-apps/account-service:1.0.1
        imagePullPolicy: Never
        ports:
        - name: http
          containerPort: 8080

