apiVersion: v1
kind: Service
metadata:
  name: order-service
spec:
  selector:
    app: order-service
    tier: backend
  ports:
  - protocol: TCP
    port: 8080
    targetPort: http

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
spec:
  selector:
    matchLabels:
      app: order-service
      tier: backend
      track: stable
  replicas: 3
  template:
    metadata:
      labels:
        app: order-service
        tier: backend
        track: stable
    spec:
      containers:
      - name: order
        image: demo-apps/order-service:1.0.1
        imagePullPolicy: Never
        ports:
        - name: http
          containerPort: 8080

