apiVersion: v1
kind: Service
metadata:
  name: portal-service
spec:
  selector:
    app: portal-service
    tier: frontend
  ports:
  - protocol: TCP
    port: 8080
    targetPort: http
  type: LoadBalancer

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: portal-service
spec:
  selector:
    matchLabels:
      app: portal-service
      tier: frontend
      track: stable
  replicas: 1
  template:
    metadata:
      labels:
        app: portal-service
        tier: frontend
        track: stable
    spec:
      containers:
      - name: portal
        image: demo-apps/portal-service:1.0.4
        imagePullPolicy: Never
        ports:
        - name: http
          containerPort: 8080

