server:
  port: 8082
  servlet:
    context-path: /
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/demo-apps
    username: root
    password: passw0rd
    driverClassName: com.mysql.jdbc.Driver
  jpa:
    database: MYSQL
    hibernate.ddl-auto: update
